version: "3.3"

services:
  http:
    build:
      context: ${COMPOSE_ROOT}/services/http
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/data/sites/
        target: /var/www/sites/
      - type: bind
        source: ${COMPOSE_ROOT}/data/caddy/caddypath/
        target: /var/caddy/
      - type: bind
        source: ${COMPOSE_ROOT}/data/caddy/uploads/
        target: /var/www/uploads
      - type: bind
        source: ${COMPOSE_ROOT}/services/http/Caddyfile
        target: /config/Caddyfile
      - type: bind
        source: /usr/share/GeoLite2-City.mmdb
        target: /usr/share/GeoLite2-City.mmdb
    environment:
      CADDYPATH: "/var/caddy"
    env_file: ${COMPOSE_ROOT}/services/http/secret.env
    ports:
      - "195.201.22.141:443:443"
      - "195.201.22.141:80:80"
    restart: always
