version: '3.7'

services:
  http:
    image: caddy:2.2.1-alpine
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/services/http/Caddyfile
        target: /etc/caddy/Caddyfile
      - type: bind
        source: ${COMPOSE_ROOT}/data/caddy/
        target: /data
    ports:
      - "195.201.22.141:443:443"
      - "195.201.22.141:80:80"
    restart: unless-stopped
