version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_LOG_MODE: 'console file'
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    ports:
      - "3000"
    volumes:
      - "${COMPOSE_ROOT}/data/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "${COMPOSE_ROOT}/data/grafana/data/:/var/lib/grafana/:rw"
      - "${COMPOSE_ROOT}/data/grafana/logs/:/var/log/grafana/:rw"
