version: "3.3"

services:
  netdata:
    image: titpetric/netdata:latest
    env_file: ${COMPOSE_ROOT}/services/netdata/secret.env
    volumes:
      - type: bind
        source: /proc/
        target: /host/proc/
      - type: bind
        source: /sys/
        target: /host/sys/

