version: "3.3"

services:
  znc_tls_proxy:
    build:
      context: ${COMPOSE_ROOT}/services/znc/
      dockerfile: Dockerfile-caddy-net
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/services/znc/Caddyfile
        target: /etc/Caddyfile
      - type: bind
        source: ${COMPOSE_ROOT}/data/caddy/caddypath-znc/
        target: /var/caddy/
    environment:
      CADDYPATH: "/var/caddy"
    env_file: ${COMPOSE_ROOT}/services/znc/secret.env
    ports:
      - "195.201.22.141:6697:6697"
    restart: always
  znc:
    build: ${COMPOSE_ROOT}/services/znc/src
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/data/znc/
        target: /znc-data/
