version: "3.3"

services:
  mtg_tls_proxy:
    build:
      context: ${COMPOSE_ROOT}/services/mtg/
      dockerfile: Dockerfile-caddy-net
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/services/mtg/Caddyfile
        target: /etc/Caddyfile
      - type: bind
        source: ${COMPOSE_ROOT}/data/caddy/caddypath-mtg
        target: /var/Caddy
    environment:
      CADDYPATH: "/var/caddy"
      ACME_AGREE: "true"
    ports:
      - "195.201.22.141:4747:4747"
    restart: always
  mtg:
    image: daenyth/servatrice
    ports:
      - "4747"
      - "4748"
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/services/mtg/servatrice.ini
        target: /root/.local/share/Cockatrice/Servatrice/servatrice.ini
