version: '3.3'

services:
  web:
    image: andrewzah/personal_site
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/services/website/andrewzah_com-keybase.txt
        target: /www/public/keybase.txt
      - type: bind
        source: ${COMPOSE_ROOT}/services/website/andrei_blue-keybase.txt
        target: /www/public/.well-known/keybase.txt
    restart: always
  isso:
    restart: always
    depends_on:
      - web
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/data/isso
        target: /data
    env_file: ${COMPOSE_ROOT}/services/website/secret.env
    build:
      context: ${COMPOSE_ROOT}/services/website
      dockerfile: Dockerfile-isso
    ports:
      - "8090"
