version: '3.7'

services:
  matterbridge:
    image: 42wim/matterbridge
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/services/matterbridge/matterbridge.toml
        target: /matterbridge.toml
