version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "${COMPOSE_ROOT}/services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "9090"
