version: "3.3"

services:
  amaranth-frontend:
    image: andrewzah/amaranth-frontend
    depends_on:
      - amaranth
    ports: 
      - "1112"
  amaranth:
    image: andrewzah/amaranth
    env_file: ${COMPOSE_ROOT}/services/amaranth/secret.env
    ports:
      - "7777"
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/data/amaranth/data
        target: /srv/amaranth/data
      - type: bind
        source: ${COMPOSE_ROOT}/data/amaranth/conf
        target: /srv/amaranth/conf
