version: "3.3"

services:
  bitlbee_tls_proxy:
    build:
      context: ${COMPOSE_ROOT}/services/bitlbee/
      dockerfile: Dockerfile-caddy-net
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/services/bitlbee/Caddyfile
        target: /etc/Caddyfile
      - type: bind
        source: ${COMPOSE_ROOT}/data/caddy/caddypath-bitlbee/
        target: /var/caddy/
    environment:
      CADDYPATH: "/var/caddy"
    ports:
      - "6667:6667"
    restart: always
  bitlbee:
    build:
      context: ${COMPOSE_ROOT}/services/bitlbee
      dockerfile: Dockerfile-bitlbee
