# https://github.com/Stanback/alpine-bitlbee-znc/blob/a86a4e007b38bd5e4751a7c5c608a248537609ff/bitlbee/Dockerfile
# Bitlbee (w/ Facebook and OTR) + Alpine Linux
#

FROM alpine:edge

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk --update add ca-certificates bitlbee-dev make automake gcc build-base abuild binutils libtool glib glib-dev git autoconf bitlbee@testing bitlbee-facebook@testing bitlbee-otr@testing && \
    adduser -h /var/lib/bitlbee -s /sbin/nologin -DH bitlbee && \
    chown -R bitlbee:bitlbee /var/lib/bitlbee && \
    touch /var/run/bitlbee.pid && \
    chown bitlbee:bitlbee /var/run/bitlbee.pid && \
    rm -rf /var/cache/apk/*

RUN mkdir /tmp/discord && cd /tmp/discord && \
    git clone https://github.com/sm00th/bitlbee-discord.git bd && cd bd && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install

USER bitlbee
VOLUME ["/var/lib/bitlbee"]
EXPOSE 6667/tcp

ENTRYPOINT ["bitlbee", "-F", "-n"]
