version: '3.3'

services:
  web_proxy:
    build:
      context: ${COMPOSE_ROOT}/services/temp-website/
      dockerfile: Dockerfile-caddy-net
    volumes:
      - type: bind
        source: ${COMPOSE_ROOT}/services/temp-website/Caddyfile
        target: /etc/Caddyfile
    environment:
      CADDYPATH: "/var/caddy"
    ports:
      - "3000:8080"
  web:
    restart: always
    image: andrewzah/clojure_main_site
    command: 'java -jar /srv/ms/ms.jar'
    volumes:
      - '.:/app/user'
